---

- name: Test ansible
  shell: sudo touch test_ansible

- name: Remove old mon
  shell: ceph mon remove hp6
  ignore_errors: yes

- name: Clear /var/run/ceph
  shell: sudo rm -r /var/run/ceph
  args:
    removes: /var/run/ceph

- name: Clear /var/lib/ceph/mon
  shell: sudo rm -r /var/lib/ceph/mon
  args:
    removes: /var/lib/ceph/mon

- name: Clear config folder
  shell: sudo rm -r /etc/ceph/
  args:
    removes: /etc/ceph

- name: Clear tmp
  shell: sudo rm /tmp/monmap
  args:
    removes: /tmp/monmap

- name: Clear mon keyring
  shell: sudo rm /tmp/ceph.mon.keyring
  args:
    removes: /tmp/ceph.mon.keyring

#- name: Delete old repo
#  shell: sudo rm -rf Tiramisu
#  args:
#    removes: Tiramisu/this_is_dev_branch

#- name: Clone ceph source code
#  shell: git clone --recursive https://github.com/SOUP-CE-KMITL/Tiramisu.git --branch develop

#- name: Change own for repo
#  shell: sudo chown -R ceph Tiramisu

#- name: Change group for repo
#  shell: sudo chgrp -R ceph Tiramisu

#- name: Install 3rd dependencies
#  shell: sudo yum install {{ item }}
#  with_items:
#    - snappy
#    - leveldb
#    - gdisk
#    - python-argparse
#    - python-ceph
#    - gperftools-libs
#    - autoconf-archive

#- name: Install dependencies
#  shell: ./install-deps.sh
#  args:
#    chdir: Tiramisu

#- name: Build autogen
#  shell: ./autogen.sh
#  args:
#    chdir: Tiramisu/ 

#- name: Build config
#  shell: ./configure 
#  args:
#    chdir: Tiramisu

#- name: Build make
#  shell: sudo make -j4
#  args:
#    chdir: Tiramisu

#- name: Install ceph
#  shell: sudo make install
#  args:
#    chdir: Tiramisu

- name: Delete config folder
  shell: sudo rm -r /etc/ceph/
  args:
    removes: /etc/ceph/ceph.conf

- name: Create dir /etc/ceph/
  shell: sudo mkdir /etc/ceph/

- name: Change own to ceph /etc/ceph/
  shell: sudo chown -R ceph /etc/ceph/

- name: Change group to ceph /etc/ceph/
  shell: sudo chgrp -R ceph /etc/ceph/

- name: Copy ceph.conf
  template: src=ceph_1_mon.conf.j2 dest=/etc/ceph/ceph.conf
         
- name: Create a keyring for your cluster and generate a monitor secret key.
  shell: ceph-authtool --create-keyring /tmp/ceph.mon.keyring --gen-key -n mon. --cap mon 'allow *'

- name: Remove old admin key
  shell: sudo rm /etc/ceph/ceph.client.admin.keyring
  args:
    removes: /etc/ceph/ceph.client.admin.keyring

- name: Generate an administrator keyring, generate a client.admin user and add the user to the keyring.
  shell: ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'

- name: Add the client.admin key to the ceph.mon.keyring.
  shell: ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring

- name: Generate a monitor map using the hostname(s), host IP address(es) and the FSID. Save it as /tmp/monmap
  shell: monmaptool --create --add {{ host }} {{ host_addr }} --fsid {{ fsid }}  /tmp/monmap

- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/ceph* /usr/lib/python2.7/site-packages/
  
- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/rados* /usr/lib/python2.7/site-packages/

- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/rbd* /usr/lib/python2.7/site-packages/

- name: Create directory mon ceph-node
  shell: sudo mkdir -p /var/lib/ceph/mon/ceph-{{ host }}

- name: Populate the monitor daemon(s) with the monitor map and keyring.
  shell: sudo /usr/local/bin/ceph-mon --mkfs -i {{ host }} --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring

- name: Change permission lib ceph
  shell: sudo chmod -R 777 /var/lib/ceph/mon/ceph-{{ host }}/

- name: Create directory var run ceph
  shell: sudo mkdir /var/run/ceph/

- name: Change permission run ceph
  shell: sudo chmod -R 777 /var/run/ceph/

- name: Reload daemon
  shell: sudo systemctl daemon-reload

- name: Start mon service
  shell: sudo systemctl restart ceph-mon@{{ host }}

- name: Distribute config
  shell: scp /etc/ceph/ceph.client.admin.keyring ceph@10.0.1.7:/home/ceph/
