---

- name: Test ansible
  shell: sudo touch test_ansible

- name: Clear /var/run/ceph
  shell: sudo rm -r /var/run/ceph
  args:
    removes: /var/run/ceph

- name: Remove var lib ceph
  shell: sudo rm -r /var/lib/ceph/
  args:
    removes: /var/lib/ceph

- name: Delete config directory
  shell: sudo rm -r /etc/ceph/
  args:
    removes: /etc/ceph/

- name: Create dir /etc/ceph/
  shell: sudo mkdir /etc/ceph/

- name: Change own to ceph /etc/ceph/
  shell: sudo chown -R ceph /etc/ceph/

- name: Change group to ceph /etc/ceph/
  shell: sudo chgrp -R ceph /etc/ceph/

- name: Clear keyring
  shell: sudo rm /etc/ceph/ceph.client.admin.keyring
  args:
    removes: /etc/ceph/ceph.client.admin.keyring

- name: Copy keyring file from mon node
  shell: sudo cp ceph.client.admin.keyring /etc/ceph/

- name: Delete old repo
  shell: sudo rm -rf Tiramisu
  args:
    removes: Tiramisu/this_is_dev_branch

- name: Clone ceph source code
  shell: git clone --recursive https://github.com/SOUP-CE-KMITL/Tiramisu.git --branch develop

- name: Copy service file
  shell: sudo cp Tiramisu/systemd/* /usr/lib/systemd/system/

- name: Change own for repo
  shell: sudo chown -R ceph Tiramisu

- name: Change group for repo
  shell: sudo chgrp -R ceph Tiramisu

- name: Install 3rd dependencies
  shell: sudo yum -y install {{ item }}
  with_items:
    - snappy
    - leveldb
    - gdisk
    - python-argparse
    - python-ceph
    - gperftools-libs
    - autoconf-archive

- name: Install dependencies
  shell: ./install-deps.sh
  args:
    chdir: Tiramisu

- name: Build autogen
  shell: ./autogen.sh
  args:
    chdir: Tiramisu/ 

- name: Build config
  shell: ./configure 
  args:
    chdir: Tiramisu

- name: Build make
  shell: sudo make -j4
  args:
    chdir: Tiramisu

- name: Install ceph
  shell: sudo make install
  args:
    chdir: Tiramisu

- name: Copy ceph.conf
  template: src=ceph_1_mon.conf.j2 dest=/etc/ceph/ceph.conf

- name: Change own to ceph /etc/ceph/
  shell: sudo chown -R ceph /etc/ceph/

- name: Change group to ceph /etc/ceph/
  shell: sudo chgrp -R ceph /etc/ceph/
         
- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/ceph* /usr/lib/python2.7/site-packages/
  
- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/rados* /usr/lib/python2.7/site-packages/

- name: Copy python-ceph local lib to lib
  shell: sudo cp /usr/local/lib/python2.7/site-packages/rbd* /usr/lib/python2.7/site-packages/

